export const enumZalo = {
  ErrorCodeTableZalo: {
    A0: { code: -100, message: 'Phát sinh lỗi không xác định' },
    A1: { code: -101, message: 'Ứng dụng gửi ZNS không hợp lệ' },
    A2: { code: -102, message: 'Ứng dụng gửi ZNS không tồn tại' },
    A3: { code: -103, message: 'Ứng dụng gửi ZNS chưa được phê duyệt' },
    A4: { code: -104, message: 'Mã secret key không tồn tại' },
    A5: { code: -105, message: 'Ứng dụng gửi ZNS chưa liên kết với OA' },
    A6: { code: -106, message: 'Phương thức không được hỗ trợ' },
    A7: { code: -107, message: 'ID ZNS không hợp lệ' },
    A8: { code: -108, message: 'Số điện thoại không hợp lệ' },
    A9: { code: -109, message: 'ID mẫu ZNS không hợp lệ' },
    A10: { code: -110, message: 'Người dùng chưa cập nhật Zalo phiên bản mới' },
    A11: { code: -111, message: 'Mẫu ZNS không có dữ liệu' },
    A12: { code: -112, message: 'Dữ liệu mẫu ZNS không hợp lệ' },
    A13: { code: -113, message: 'Nút không hợp lệ' },
    A14: {
      code: -114,
      message:
        'Người dùng không nhận được ZNS vì các lý do: Trạng thái tài khoản, Tùy chọn nhận ZNS, Sử dụng Zalo phiên bản cũ, hoặc các lỗi nội bộ khác',
    },
    A15: { code: -115, message: 'Ví không đủ số dư' },
    A16: { code: -116, message: 'Nội dung không hợp lệ' },
    A17: {
      code: -117,
      message: 'OA hoặc ứng dụng gửi ZNS chưa được cấp quyền sử dụng mẫu ZNS này',
    },
    A18: {
      code: -118,
      message:
        'Số điện thoại chưa đăng ký Zalo hoặc người dùng đã vô hiệu hóa tài khoản hơn 30 ngày',
    },
    A19: { code: -119, message: 'Tài khoản không thể nhận ZNS' },
    A20: { code: -120, message: 'OA chưa được cấp quyền sử dụng tính năng này' },
    A21: { code: -121, message: 'Mẫu ZNS không có nội dung' },
    A22: { code: -122, message: 'Nội dung mẫu ZNS không đúng định dạng json' },
    A23: { code: -123, message: 'Không giải mã được nội dung mẫu ZNS' },
    A24: { code: -124, message: 'Mã truy cập không hợp lệ' },
    A25: { code: -125, message: 'ID OA không hợp lệ' },
    A26: { code: -126, message: 'Ví (development mode) không đủ số dư' },
    A27: { code: -127, message: 'Template test chỉ có thể được gửi cho admin' },
    A28: { code: -128, message: 'Ứng dụng gửi ZNS chưa có mã encoding' },
    A29: { code: -129, message: 'Mã encoding không thể được tạo ra' },
    A30: { code: -130, message: 'Nội dung mẫu ZNS vượt giới hạn kí tự' },
    A31: { code: -131, message: 'Mẫu ZNS chưa được phê duyệt' },
    A32: { code: -132, message: 'Tham số không hợp lệ' },
    A33: { code: -133, message: 'Không hỗ trợ gửi ZNS trong khung giờ 22h đến 6h' },
    A34: { code: -134, message: 'Người dùng chưa phản hồi gợi ý nhận ZNS từ OA' },
    A35: { code: -135, message: 'OA chưa được cấp quyền gửi ZNS' },
    A36: {
      code: -136,
      message: 'Ứng dụng gửi ZNS cần được kết nối với ZBA để sử dụng các tính năng trả phí',
    },
    A37: {
      code: -137,
      message:
        'ZBA kết nối với ứng dụng gửi ZNS này đã hết số dư tài khoản hoặc không thể thanh toán',
    },
    A38: { code: -138, message: 'Ứng dụng gửi ZNS chưa có quyền sử dụng tính năng này' },
    A39: { code: -139, message: 'Người dùng đã từ chối nhận loại ZNS này' },
    A40: { code: -140, message: 'OA chưa được cấp quyền gửi ZNS hậu mãi cho người dùng này' },
    A41: { code: -141, message: 'Người dùng từ chối nhận ZNS từ OA' },
    A42: { code: -142, message: 'OA chưa có RSA key, vui lòng gọi API tạo RSA key' },
    A43: { code: -143, message: 'OA đã có RSA key, vui lòng gọi API get RSA key' },
    A44: { code: -144, message: 'OA đã vượt quá số lượng gửi cho phép trong ngày hôm nay' },
    A45: { code: -145, message: 'OA không được phép gửi loại nội dung ZNS này' },
    A46: { code: -146, message: 'Mẫu ZNS này đã bị vô hiệu hóa do chất lượng thấp' },
    A47: {
      code: -147,
      message: 'OA đã vượt quá số lượng gửi cho phép của mẫu ZNS này trong ngày hôm nay',
    },
    A48: { code: -148, message: 'Không tìm thấy ZNS journey token' },
    A49: { code: -149, message: 'ZNS journey token không hợp lệ' },
    A50: { code: -150, message: 'ZNS journey token đã hết hạn' },
    A51: { code: -151, message: 'Lấy E2EE key thất bại, vui lòng thử lại sau' },
    A52: { code: -152, message: 'Mẫu ZNS này không phải mẫu E2EE' },
  },
};
